FORMAT: 1A

# OutOfCopyright
This is a development document of how the API of OutOfCopyright.eu could look like.

## API Collection [/]
### List all countries [GET]
+ Response 200 (application/json)

        {
            "countries": [
                {
                    "name": "Belgium",
                    "url": "http://api.outofcopyright.eu/Belgium"
                },
                {
                    "name": "France",
                    "url": "http://api.outofcopyright.eu/France"
                },
                {
                    "name": "Germany",
                    "url": "http://api.outofcopyright.eu/Germany"
                },
                {
                    "name": "Luxembourg",
                    "url": "http://api.outofcopyright.eu/Luxembourg"
                }
            ]
        }


## Countries [/{country}/]
The API for a specific country, provides a list of decision trees.

+ Parameters
    + country (required, string, ``) ... Name of the country

### List type of work of a given country [GET]
+ Response 200 (application/json)

        {
            "categories": [
                {
                    "name": "Phonogram",
                    "url": "http://api.outofcopyright.eu/Belgium/Phonogram"
                },
                {
                    "name": "Unoriginal Database",
                    "url": "http://api.outofcopyright.eu/Belgium/Unoriginal%20Database"
                }
            ]
        }
        
+ Response 404 (application/json)

        {
            "errormessage" : "No country at this address, please go to api.outofcopyright.eu for a full overview of our API"
        }


## Calculator [/{country}/{category}]
Calculation calculator

+ Parameters
    + country (required, string, ``) ... Name of the country
    + category (required, string, ``) ... Name of the decision tree you want to use

### Retrieve parameter for a calculation [GET]
+ Response 200 (application/json)

        {
            "parameters": [
                {
                    "id": "PUBLICATION_DATE",
                    "question": "Publication date",
                    "additional_information": "Publication date",
                    "type": "numeric"
                },
                {
                    "id": "CREATION_DATE",
                    "question": "Creation date",
                    "type": "numeric"
                },
                {
                    "id": "COMMUNICATION_DATE",
                    "question": "What is the communication date of the work?",
                    "type": "numeric"
                },
                {
                    "id": "EEA_NOTEEA",
                    "question": "Operations genuinely linked with",
                    "type": "list",
                    "items": [ "EEA", "Not EEA" ]
                },
            ]
        }


### Send a calculation request [POST]
+ Request (application/json)

        { 
            "PUBLICATION_DATE" : "1940",
            "CREATION_DATE" : "1940",
            "COMMUNICATION_DATE" : "1940"
        }

+ Response 200 (application/json)
        
        {
            "calculator" : "api.outofcopyright.eu/belgium/phonogram/",
            "version" : "<commit hash?>",
            "parameters" : [
                "PUBLICATION_DATE" : "1940",
                "CREATION_DATE" : "1940",
                "COMMUNICATION_DATE" : "1940"
            ],
            "result" : “Out Of Copyright”
        }

+ Response 400 (application/json)

        {
            "calculator" : "api.outofcopyright.eu/belgium/phonogram/",
            "version" : "<commit hash?>",
            "parameters" : [
                "PUBLICATION_DATE" : "1940"
            ],
            "missing_parameters" : [
                "CREATION_DATE",
                "COMMUNICATION_DATE"
            ],
            "errormessage" : "Some parameters are missing"
        }

+ Response 404 (application/json)

        [{
            "errormessage" : "No calculator at this address, please go to api.outofcopyright.eu for a full overview of our API"
        }]

