FORMAT: 1A

# OutOfCopyright
This document contains documentation on how the API of OutOfCopyright.eu works.

## API Collection [/]
### List all countries [GET]
+ Response 200 (application/json)

        {
            "countries": [
                {
                    "name": "Belgium",
                    "url": "http://api.outofcopyright.eu/Belgium"
                },
                {
                    "name": "France",
                    "url": "http://api.outofcopyright.eu/France"
                },
                {
                    "name": "Germany",
                    "url": "http://api.outofcopyright.eu/Germany"
                },
                {
                    "name": "Luxembourg",
                    "url": "http://api.outofcopyright.eu/Luxembourg"
                }
            ]
        }


## Countries [/{country}/]
The API for a specific country, provides a list of decision trees.

+ Parameters
    + country (required, string, ``) ... Name of the country

### List type of work of a given country [GET]
+ Response 200 (application/json)

        {
            "categories": [
                {
                    "name": "Phonogram",
                    "url": "http://api.outofcopyright.eu/Belgium/Phonogram"
                },
                {
                    "name": "Unoriginal Database",
                    "url": "http://api.outofcopyright.eu/Belgium/Unoriginal%20Database"
                }
            ]
        }
        
+ Response 404 (application/json)

        {
            "error": 8,
            "message": "Country not found"
        }


## Calculator [/{country}/{category}]
Calculation calculator

+ Parameters
    + country (required, string, ``) ... Name of the country
    + category (required, string, ``) ... Name of the decision tree you want to use

### Retrieve parameter for a calculation [GET]
+ Response 200 (application/json)

         {
            "parameters": [
               {
                    "id": "When_was_the_fixation_of_the_performance_first_made_public",
                    "type": "numeric",
                    "question": "When was the fixation of the performance first made public?",
                    "items": null
                },
                {
                    "id": "When_did_the_performance_take_place",
                    "type": "numeric",
                    "question": "When did the performance take place?",
                    "items": null
                }
            ]
        }


### Send a calculation request [POST]
+ Request (application/json)

        { 
            "In_what_year_was_the_phonogram_published": 1950,
            "In_what_year_was_the_phonogram_created": 1950
        }

+ Response 200 (application/json)
        
        {
            "URL": "http://api.outofcopyright.eu/Netherlands/Phonogram",
            "version": "50af4193cfb401cc17d6e4cbbabc8a6883330a88",
            "parameters": {
                "In_what_year_was_the_phonogram_published": 1950,
                "In_what_year_was_the_phonogram_created": 1950
            },
            "result": "The related right of the producer of the phonogram has expired. Please note that a single item might be protected by multiple layers of rights. You may need to apply the Public Domain Calculator again to examine whether additional rights apply, such as copyright protection in any underlying literary or artistic work or performers' rights in any performance that may be fixated in the phonogram."
        }

+ Response 400 (application/json)

        {
            "URL": "http://api.outofcopyright.eu/Netherlands/Phonogram",
            "version": "50af4193cfb401cc17d6e4cbbabc8a6883330a88",
            "parameters": {
                "In_what_year_was_the_phonogram_published": 1950
            },
            "result": {
                "error": 1,
                "waiting_response": "In_what_year_was_the_phonogram_created",
                "question": "",
                "correct_responses": "Numeric value",
                "all_possible_responses": [
                    "In_what_year_was_the_phonogram_communicated_to_the_public",
                    "In_what_year_was_the_phonogram_created"
                ]
            }
        }

+ Response 404 (application/json)

        {
            "error": 9,
            "message": "Type of work not found"
        }
